data:
  _target_: features.autoencoder.TimeSeriesDataset
  batch_size: 8
  categorical_cols: [ ]
  target_col: [ ]
  prediction_window: 0

training:
  denoising: False
  directions: 1
  gradient_accumulation_steps: 1
  hidden_size_encoder: 1024
  hidden_size_decoder: 1024
  input_att: False
  lr: 0.005
  lrs_step_size: 5000
  max_grad_norm: 0.5
  num_epochs: 50
  reg1: True
  reg2: False
  reg_factor1: 0.0001
  reg_factor2: 0.0001
  reg_sr: 0.0001
  seq_len: 1
  temporal_att: True

general:
  do_eval: True
  do_train: True
  logging_steps: 50

  output_dir: "/root/inovest/mlframework/output"
  save_steps: 200
  eval_during_training: True